### ISSUE TITLE
add support to VMware guest os customization

### ISSUE THREAD

**Issue by maxadamo** [AlmaLinux/cloud-images#10]
The title is slightly wrong as you can't add support. But you could ask VMware to support Almalinux. 
I noticed seen that you have created packer templates for VMware, but unfortunately, it is not possible to use Terraform against the template to customize the OS. 
This is the error that I get:
```
Error: 
Virtual machine customization failed on "/XXXX/vm/YYYYY/aaa_almalinux8/test/test-almalinux01":

An error occurred while customizing VM test-almalinux01. For details reference the log file <No Log> in the guest OS.
```

and it's due to a lack of support from VMware.
There is another issue open as well: https://github.com/vmware/open-vm-tools/issues/497

**Comment by tenthirtyam** [comment]
Supported on vSphere 7.0 U3d or later (vSphere 6.5 and 6.7 are end of general support).

Recommend: close

**Comment by LKHN** [comment]
@tenthirtyam Thanks!
