### ISSUE TITLE
Support EFI boot AlmaLinux 9.0

### ISSUE THREAD

**Issue by ympan** [AlmaLinux/cloud-images#105]
Hello!
Looks like it is a related issue, what was solved for Almalinux 8
https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-UEFI-8.6-20220718.x86_64.qcow2
https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/ - where are NO UEFI images
But is more interested for me that there is no support in kickstart:
WARNING:anaconda.modules.storage.partitioning.automatic.noninteractive_partitioning:gpt is not a supported disklabel type on this platform. Using default disklabel msdos instead.

related issue from my point of view:
https://github.com/AlmaLinux/cloud-images/issues/74

**Comment by LKHN** [comment]
Hello @ympan,
Thanks for the reporting.
The default AlmaLinux OS 9 Generic Cloud image supports BIOS and UEFI with the GPT partition table:

Here's the BIOS+UEFI support on the kickstart file:

https://github.com/AlmaLinux/cloud-images/blob/f8c286b17e664dfe7b5178366970d4ed321666ac/http/almalinux-9.gencloud-x86_64.ks#L25-L36
