### ISSUE TITLE
No DigitalOcean images for AlmaLinux 9?

### ISSUE THREAD

**Issue by refi64** [AlmaLinux/cloud-images#109]
Hello!

I just noticed that it seemed strange that there are no DO images for AlmaLinux 9. Is this planned and just bottlenecked on lack of time, or are there any outstanding blockers anywhere, or...?

**EDIT:** also worth noting the latest release is for still for 8.5 as well, not 8.6 yet :sweat_smile:

**Comment by LKHN** [comment]
Hi Ryan,

Thanks for the question.

In DO there are two types of images, Regular and Custom Import.

For the first one, we created some PRs to help speed up the process. Unfortunately, they closed our PRs and reverted some of them to not add the AlmaLinux OS support. You can read their explanation from [here](https://github.com/digitalocean/marketplace-partners/pull/141)

We released the image files and instructions on how to import them as a custom image, however, after some unhappy users' feedback about the limitations of the custom images, we haven't released the 8.6 yet. 

See: https://ideas.digitalocean.com/core-compute-platform/p/possibility-for-almalinux

Our PRs:

https://github.com/digitalocean/marketplace-partners/pull/141

https://github.com/digitalocean/marketplace-partners/pull/143

https://github.com/digitalocean/droplet-1-clicks/pull/45

https://github.com/digitalocean/droplet-agent/pull/32

**Comment by LKHN** [comment]
I just checked, AlmaLinux OS 8 and AlmaLinux 9 available as regular images now!
