### ISSUE TITLE
Virtualbox anaconda error

### ISSUE THREAD

**Issue by KAPPAsper** [AlmaLinux/cloud-images#120]
when I use virtualbox to build an ova image I will get this error: 
`Failed to fetch kickstart from http://10.0.2.2:8456/almalinux-8.vagrant.ks` 

Command I use: `packer build -only=virtualbox-iso.almalinux-8 .`
versions: virtualbox 7.0.4-1 packer 1.8.4-1

The packer step it gets stuck: `==> virtualbox-iso.almalinux-8: Waiting for SSH to become available...` 
But that's expected as the kickstart doesn't happen

**Comment by LKHN** [comment]
Dear @KAPPAsper ,

Yes, I faced this issue too when I tried to build the initial versions of 8.7 and 9.1 vagrant boxes, then I had to build them on VirtualBox `6.1.40` . It's in TODO list to get all logs and outputs from `6.1.40` and `7.0.4` compare the differences to determine whether the plugin creates a VM with different configuration on `7.x` and file a bug report for Packer's virtualbox plugin[^1]

[^1]: https://github.com/hashicorp/packer-plugin-virtualbox
