### ISSUE TITLE
Add support for Azure images

### ISSUE THREAD

**Issue by ksquires** [AlmaLinux/cloud-images#14]
I saw the issue filed for AWS, but didn't see one open/closed for Azure.   A quick peek in the Azure marketplace only shows Almalinux images from 3rd party.

**Comment by ksquires** [comment]
> @ksquires thanks for opening an issue. coming real soon 😉. Do you use lots of compute on azure?

At this time, not much.  I just like to be prepared :)

**Comment by johanburati** [comment]
There is an **AlmaLinux** image from **AlmaLinux OS Foundation** on the **Azure Marketplace** now.
- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux

![image](https://user-images.githubusercontent.com/106444/129820278-9c714b1a-5773-47a2-9a04-dbab17603cad.png)

**Comment by jaboutboul** [comment]
Azure supported was added a while ago. See https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux for reference.
