### ISSUE TITLE
9.2 Vagrant-boxes are much bigger than 9.1

### ISSUE THREAD

**Issue by alexgit2k** [AlmaLinux/cloud-images#140]
The Vagrant-boxes for 9.2 are much bigger than the ones for 9.1 (see https://app.vagrantup.com/almalinux/boxes/9):
| Provider   | 9.0          | Increase  | 9.1         | Increase | 9.2        |
| ---------- | --------- | --------- | -------- | --------- | -------- |
| Virtualbox | 598 MB  | 11%        | 664 MB | 40%       | 932 MB |
| Libvirt       | 505 MB  | 9%          | 552 MB | 30%       | 719 MB |

I tried to use an 9.1 box as base, updated to 9.2 and then created the box with:
```
dnf -y update
dnf -y remove kernel-devel gcc binutils make bzip2 elfutils-libelf-devel
dnf -y remove --oldinstallonly kernel
dnf -y autoremove
dnf clean all
truncate -s0 /var/log/*.log /var/log/*/*.log
exit

vagrant package
```

The resulting box for Virtualbox has a size of 754 MB, which is still 14% bigger, but far away from the 40%.

I do not see any updates in this repository for 9.2, so haven't the 9.2 boxes built the same way as 9.1?

**Comment by LKHN** [comment]
Hi @alexgit2k , Thanks such detailed issue and your attention. 

Which VirtualBox version did you build the 9.2 box?


Those are only changes we have made:

- Finally found the [workaround](https://github.com/hashicorp/packer-plugin-virtualbox/issues/104) and built it in VirtualBox 7.0 (`7.0.8`).
- Now one box supports BIOS and UEFI at the same time, it's UEFI by default.

I will push the changes shortly.

**Comment by alexgit2k** [comment]
I was also using Virtual Box 7.0.8.

So the 9.1 boxes did not support BIOS & UEFI at the same time? Could this be the cause for an increase of about 200 MB (exclusive updates)?

**Comment by LKHN** [comment]
Yes, true all vagrant boxes for virtualbox provider was BIOS only before the 9.2 release.

Built the BIOS only version and its size is 817 MiB and it has 20 less packages than the BIOS+UEFI version:

So yes, the UEFI support brings own packages with it.

```
dmidecode
efi-filesystem
efibootmgr
efivar-libs
flashrom
fwupd
fwupd-plugin-flashrom
grub2-efi-x64
json-glib
libgcab1
libgudev
libgusb
libjcat
libsmbios
libusbx
libxmlb
mokutil
polkit-libs
shared-mime-info
shim-x64
```

**Comment by LKHN** [comment]
@alexgit2k Thanks for the feedback!

It is `587.46 MB` now starting with the [9.5.20241203](https://portal.cloud.hashicorp.com/vagrant/discover/almalinux/9) version. Feel free to open a new issue if you notice something on the image sizes again.
