### ISSUE TITLE
Vagrant 9.3 image is missing

### ISSUE THREAD

**Issue by vchepkov** [AlmaLinux/cloud-images#166]
Vagrant 9.3 image is still missing, could you publish it, please?

**Comment by LKHN** [comment]
Hi @vchepkov, Starting with the 8.9 and 9.3 versions, we uploaded the boxes through the second version of Vagrant Cloud API. This new version of API brings multi-architecture support with a cost; Vagrant cannot find the new version if the source of the box URL is changed.

OLD:
https://app.vagrantup.com/almalinux/boxes/9/versions/9.2.20230513/providers/virtualbox/unknown/vagrant.box

NEW:
https://app.vagrantup.com/almalinux/boxes/9/versions/9.3.20231118/providers/virtualbox/amd64/vagrant.box

When we start to upload the 9.3 and 8.9 boxes, we chose the `amd64` as a default architecture with a expectation that Vagrant would translate unknown to the amd64 in the source URL and find the new version of the installed box. Evidently, It's not working in this way (for now).

I can offer this workaround which I had to use myself:

`vagrant box update --box almalinux/8`
`vagrant box update --box almalinux/9`

When you issue the `vagrant box list`, you will see the architecture of the box inside the parenthesis.

**Comment by vchepkov** [comment]
@LKHN , thank you, your workaround worked, but, FYI, there is no architecture listed in the output
```
$ vagrant box list
almalinux/8 (virtualbox, 8.8.20230606)
almalinux/9 (virtualbox, 9.2.20230513)
```

**Comment by LKHN** [comment]
@vchepkov Why your output doesn't show the 8.9 and 9.3 versions despite you updated the boxes manually?

**Comment by vchepkov** [comment]
That was before I ran the updates, it now shows updated versions (after prune)
```
$ vagrant box list
almalinux/8 (virtualbox, 8.9.20231219)
almalinux/9 (virtualbox, 9.3.20231118)
```

**Comment by LKHN** [comment]
Seems like the output is different on the different vagrant provider :thinking:

```sh
$ vagrant box add almalinux/9
==> box: Loading metadata for box 'almalinux/9'
    box: URL: https://vagrantcloud.com/api/v2/vagrant/almalinux/9
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) hyperv
2) libvirt
3) virtualbox
4) vmware_desktop

Enter your choice: 2
==> box: Adding box 'almalinux/9' (v9.3.20231118) for provider: libvirt (amd64)
    box: Downloading: https://vagrantcloud.com/almalinux/boxes/9/versions/9.3.20231118/providers/libvirt/amd64/vagrant.box
    box: Calculating and comparing box checksum...
==> box: Successfully added box 'almalinux/9' (v9.3.20231118) for 'libvirt (amd64)'!
$ vagrant box list
almalinux/9 (libvirt, 9.3.20231118, (amd64))

```

**Comment by LKHN** [comment]
@vchepkov Hi, Did you get the 9.4 version of box as an  available update?

**Comment by vchepkov** [comment]
@LKHN , yes thank you, it worked as expected this time
