### ISSUE TITLE
open-vm-tools not running using generic cloud image with vsphere

### ISSUE THREAD

**Issue by Keltirion** [AlmaLinux/cloud-images#189]
I'm trying to use Alma 9.4 (same for Alma 8) Generic cloud image with vsphere and cloud-init but when i create sample vm seems like open-vm-tools is not running? My vsphere version is 7.0.3.01900

<img width="798" alt="obraz" src="https://github.com/user-attachments/assets/0dcbeaf5-88f0-414d-8f5e-c6797981fbbf">

I'm passing cloud-init configuration with terraform but it does not work. Am I doing something wrong here? I can see it being added to the VM

```
  extra_config = {
    "guestinfo.metadata" = base64encode(file(local.vm_meta_config))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata" = data.cloudinit_config.main.rendered
    "guestinfo.userdata.encoding" = "base64"
  }
```
and the contents are correct

<img width="842" alt="obraz" src="https://github.com/user-attachments/assets/c503e04c-1722-451c-8ecf-4f1dd5e5835e">

**Comment by LKHN** [comment]
Hi Lech,

The `open-vm-tools` is [excluded](https://github.com/AlmaLinux/cloud-images/blob/2880bc2567ee2ce1ff4925893f43e70cd7139105/http/almalinux-9.gencloud-x86_64.ks#L52) on the kickstart files of Generic Cloud images and is not installed by the Ansible packer provisioner. So, it is expected to not have it installed at all.

Can you build the image from the sources by commenting the line that `open-vm-tools` excluded and add it to the list of installed packages?

Currently, I don't have any access to VMWare vSphere to try to reproduce the issue related to Cloud-init at the moment.

**Comment by Keltirion** [comment]
Hi i did create my own custom version with Packer and open-vm-tools now everything works.

**Comment by LKHN** [comment]
@Keltirion ,

Thanks for the feedback. Can we say that including only `open-vm-tools` package is enough to make Generic Cloud compatible with VMware vSphere? Can you share which else changes you have to made to make it work?

**Comment by Keltirion** [comment]
@LKHN I think so, I've used standard alma linux image not the generic cloud one, using kickstart i did the instalation of open-vm-tools and some config. AFIK open-vm-tools is need to report back to vsphere packer provisioner the ip of vm after first install. After that rest works fine.
