### ISSUE TITLE
Provide Azure ARM images with 64k page size kernel

### ISSUE THREAD

**Issue by andrewlukoshko** [AlmaLinux/cloud-images#192]
We see some demand in Azure ARM images with 64k page size kernel.

The offer naming should be the following:
```
almalinux:almalinux-arm-64k
```

It's recommended to use the following code in kickstart to switch to 64k kernel:
```
%packages
kernel-64k
-kmod-kvdo
-vdo
-kernel
```

**Comment by LKHN** [comment]
Instead of creating a new offer. It may better to create a new plan which only affects SKU part of the URN.
So, in addition to the current SKUs:
- `almalinux:almalinux-arm:8-arm-gen2`
- `almalinux:almalinux-arm:9-arm-gen2`

The new one can be added as:
- `almalinux:almalinux-arm:9-arm-64k-gen2`

**Comment by LKHN** [comment]
Published as a new plan on https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux-arm
