### ISSUE TITLE
Maintain latest-symlink for GenericCloud image

### ISSUE THREAD

**Issue by fbhdk** [AlmaLinux/cloud-images#21]
Nice-to-have:   In the images directory on mirrors containing the GenericCloud image, it would be nice to maintain a symlink to latest build of a major release.

This makes it much easier to maintain automatic local updates of images rather than having to parse filelists.

**Comment by ezamriy** [comment]
Agree, that will be handy. Especially if use it in combination with the ETag HTTP header so you will download a new image only if it has been changed.

**Comment by andrewlukoshko** [comment]
Hi!
Symlink to latest image has been added:
https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/
Thanks for idea @fbhdk
