### ISSUE TITLE
Not really a bug, but why?

### ISSUE THREAD

**Issue by adontz** [AlmaLinux/cloud-images#24]
`sudo ls -R -l -a /root/` on a newly created AWS image returns 

```
/root/:
 .   ..   .bash_history   .bash_logout   .bash_profile   .bashrc   .cshrc  '~ezamriy'   .ssh   .tcshrc

/root/~ezamriy:
.  ..  .ansible

/root/~ezamriy/.ansible:
.  ..  tmp

/root/~ezamriy/.ansible/tmp:
```

**Comment by ezamriy** [comment]
Yeah, that is garbage left by Ansible and I'm still trying to understand why. Anyway, I have a workaround and we should have updated AMIs this week with #23 fixed.
