### ISSUE TITLE
AlmaLinux cloud image with GPT partition table?

### ISSUE THREAD

**Issue by rptaylor** [AlmaLinux/cloud-images#33]
Hello,

Thanks for AlmaLinux!

RHEL8 cloud images downloaded from here:
https://access.redhat.com/downloads/content/479/
```
 Red Hat Enterprise Linux 8.4 Update KVM Guest Image
Last modified:     2021-05-18
SHA-256 Checksum:   df9660e770711f797b311a04946ce45db19843ddb1c60ccadca8b77fa0444e4f 
```
come with a GPT partition table. However the AlmaLinux-8.4-x64-2021-06 VM image has a MSDOS partition table.  This makes it impossible to use more than 2 TB of storage (max MSDOS partition size) in the root disk volume.

Could a AlmaLinux image be provided that uses a GPT table (like RHEL) instead of MSDOS?

Thanks!

**Comment by LKHN** [comment]
@rptaylor Hey! Thanks for the helpful feedback. stay tuned for the next build :)

**Comment by rptaylor** [comment]
@LKHN Okay great, thanks I will! Any ETA for the next image?  :)

**Comment by rptaylor** [comment]
Any idea if images with GPT partition tables are on the horizon?

(for reference)
```
$ guestfish --ro -a AlmaLinux-8-GenericCloud-8.4-20210727.x86_64.qcow2

><fs> launch
><fs> list-partitions
/dev/sda1
><fs> part-get-parttype /dev/sda
msdos
```

**Comment by LKHN** [comment]
@rptaylor AlmaLinux OS 8.5 Generic Cloud Images default on GPT available on: https://wiki.almalinux.org/cloud/Generic-cloud.html

**Comment by rptaylor** [comment]
Thanks! I'll give them a try soon!

**Comment by srbala** [comment]
@rptaylor after your verification, you can close this issue, thank you
