### ISSUE TITLE
Additional smaller Azure image

### ISSUE THREAD

**Issue by Kulesza** [AlmaLinux/cloud-images#53]
The actual AlmaLinux image for Azure VMs is 30 GB big. Thats lot of space, if just a minimal installation (2GB) and a web server or a python program is necessary.

VMs can be turned off and changed in size. So the costs can be controlled dynamically and minimized.

But storage can only be increased in size. And you pay for the reserved and not the used storage. So the minimum is always a 30 GB OS disk. When there would be a possibility to choose a 4GB minimal image, the costs for SSD disks could be reduced around 75% and more.

For one VM it is not much, but when you build a lab, test or productive environment with a lot of VMs, this would have an immense impact on the monthly bill.

**Comment by srbala** [comment]
@Kulesza would be able to contribute this issue

**Comment by Kulesza** [comment]
Sure, how can I help?

**Comment by LKHN** [comment]
@Kulesza Hi, thanks for the feedback. 30 GB OS disk size is on of the Commercial marketplace certification policies. Therefore, we need need to continue to use this size to pass from the certification. Since the sources available, feel free to build your VM image with a custom size.
