### ISSUE TITLE
Almalinux 8.5 images

### ISSUE THREAD

**Issue by navjotjsingh** [AlmaLinux/cloud-images#54]
Almalinux 8.5 is out. When can we expect the newer images?

**Comment by srbala** [comment]
@navjotjsingh main images are alreay in dockerhub https://hub.docker.com/_/almalinux?tab=tags ready to use.

**Comment by srbala** [comment]
imm over looked, team is working on it

**Comment by sjansen1** [comment]
Today i looked up on the official images and in Azure 8.5 is finaly there.

Get-AzVMImageSku -Location westeurope -PublisherName almalinux -Offer almalinux | Select Skus            

Skus
----
8_4
8_4-gen2
8_5
8_5-gen2

Is there a reason why #14 is still open? for me everything looks good.

**Comment by jaboutboul** [comment]
Closing. See: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux
