### ISSUE TITLE
attach interface wont work

### ISSUE THREAD

**Issue by rfakit** [AlmaLinux/cloud-images#71]
in Openstack attach interface wont work.

can not get IP address,. Centos is ok but alma is not.

**Comment by rfakit** [comment]
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:80:f9:f3 brd ff:ff:ff:ff:ff:ff

the second inf will be like this
IP can no be assigned

**Comment by LKHN** [comment]
Hey! @rfakit I assume you're using the `x86_64` image. I couldn't reproduce the issue. It assigns an IP to the second and third interface immediately. :thinking:

**Comment by rfakit** [comment]
I am using this AlmaLinux-8-GenericCloud-8.4-20210727.x86_64.qcow2 image.
can u send me cloud.cfg of your Image

**Comment by LKHN** [comment]
Could you test the latest image of the 8.5 release from here? : https://wiki.almalinux.org/cloud/Generic-cloud.html#download-and-verification

I did my test with the `AlmaLinux-8-GenericCloud-8.5-20211119.x86_64.qcow2 image`

**Comment by rfakit** [comment]
I test it but no success. 
You know Centos has flaw too. We shoud install NetworkManager inside it and change cloud.cfg inorder to make it workable.now Centos is OK.
i user packer to create this kind of custom image, I did the same approchage for Alma. but nothing happened. I tested both edited and official version of your Image.

**Comment by rfakit** [comment]
I used this link
https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-latest.x86_64.qcow2
its the same with the link that you sent "AlmaLinux-8-GenericCloud-8.5-20211119.x86_64.qcow2 image"

**Comment by LKHN** [comment]
It's the `/etc/cloud/cloud.cfg` file that you've requested before. Could you enlighten me about the flaw CentOS and Alma has? any link to the bug report if it's a known issue ? :thinking: 
[cloud-etc.cfg.txt](https://github.com/AlmaLinux/cloud-images/files/7807418/cloud-etc.cfg.txt)

**Comment by rfakit** [comment]
you know its all about cloud-init and datasources.
thats the reason that there is no bug links available. the word flaw is not for that meaning. my english is not good. excuse my language.

**Comment by rfakit** [comment]
i fixed it
with these files.
[cloud.zip](https://github.com/AlmaLinux/cloud-images/files/7808601/cloud.zip)
it was all about cloud-init. try to invest these files. 
main image dose only have one file in cloud.cfg.d directory.

**Comment by LKHN** [comment]
@rfakit Thanks for the reporting and the cloud-init files! I'll explore these files :thinking:
