### ISSUE TITLE
Support EFI boot

### ISSUE THREAD

**Issue by nijave** [AlmaLinux/cloud-images#74]
It looks like the generic cloud image only supports BIOS boot. It'd be nice if there were an image supporting UEFI which would allow it to work on Hyper-V Gen 2 VMs (and maybe other things)

Here's some sample changes https://github.com/AlmaLinux/cloud-images/compare/master...nijave:nv-gencloud-efi?expand=1

I didn't test whether this works with Secure Boot but I'm not worried about that for my use. The qemu `-bios` file path is for Fedora--not sure if/when it may vary.

**Comment by adamo-ovh** [comment]
I agree with this request. Ubuntu (since 18.04) and Debian (since Debian 11) has been providing their cloud generic images which are EFI compliant. Would be good to see Almalinux also providing EFI compliant images.

**Comment by LKHN** [comment]
Good news! 

The Generic Cloud UEFI Image on the `x86_64`,  is available for download on https://wiki.almalinux.org/cloud/Generic-cloud.html ! as the `AlmaLinux-8-GenericCloud-UEFI-latest.x86_64.qcow2` and `AlmaLinux-8-GenericCloud-UEFI-8.5-YYYYMMDD.x86_64.qcow2`
