### ISSUE TITLE
Packer files for Azure

### ISSUE THREAD

**Issue by cavemandaveman** [AlmaLinux/cloud-images#75]
I see there are Packer files for AWS and DigitalOcean in this repo, but none for Azure. Why is that? There is an  [official Alma Linux Azure Marketplace offering](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/almalinux.almalinux) - it would be nice to see the source for it in this repo.

**Comment by tbugfinder** [comment]
... including the HPC customisation.

**Comment by EE041B3-UnionInvestment** [comment]
@ezamriy can you publish those files? Guess we would need some hyper-v host to build the image or something?

**Comment by ctophs** [comment]
@ezamriy may I ask: can you publish what you did to do the azure images? Guess one would need an azure hyper-v host or something?

**Comment by TheBlackMini** [comment]
Any chance on an update for this issue?

**Comment by cavemandaveman** [comment]
Thank you!
